### PR TITLE
Update after running for Home Delivery subs

### PR DESCRIPTION
**Pull request by paulbrown1982**
- Tweak to not make all the calls at once, and instead control the parallelisation. In the end it I ran it in series.
- Adding timings to give an idea of how long the script will take (1500ms)
- Removed semicolons as this is ES6 code.

cc @jacobwinch @AWare @pvighi @lmath @johnduffell

### CODE REVIEW

**Comment by johnduffell** [comment]
looks ok to me, as long as it works! 👍

**Comment by pvighi** [comment]
@paulbrown1982  I guess we should close this one at this point

**Comment by paulbrown1982** [comment]
Or merge it?

**Comment by pvighi** [comment]
true, one of the two, it's been approved over 2 years ago

**Pull request merged**
